name: mentorx_mvp
description: MentorXP MVP (flutter)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+5

environment:
  sdk: ">=2.2.2 <3.0.0-85.0.dev"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  convex_bottom_bar:
  cloud_firestore:
  animated_text_kit:
  firebase_core:
  firebase_auth:
  firebase_storage:
  path:
  modal_progress_hud:
  provider:
  font_awesome_flutter:
  page_transition:
  dropdownfield:
  equatable:
  image_picker:
  cached_network_image:
  image:
  firebase_messaging:
  intl: ^0.17.0
  lottie: ^1.4.2
  dropdown_button2: ^1.9.2
  carousel_slider: ^4.2.1






dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: RockSalt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf


  assets:
    - assets/images/MentorXP.png
    - assets/images/MentorXPDark.png
    - assets/images/MXPDark.png
    - assets/images/defaultCover.png



